Start: Preparation initial config
AliMD/One pull request #1
Opened 2021-12-26 19:23 UTC by njfamirm

2021-12-27 22:05 UTC, AliMD requested changes
Thanks

2021-12-27 22:05 UTC, AliMD commented on package.json
> +  "name": "one",
@one/...

2021-12-27 22:05 UTC, AliMD commented on package.json
> +  "name": "one",
Turn it private

2021-12-27 22:05 UTC, AliMD commented
@asmanp2012 please review

2021-12-29 11:55 UTC, asmanp2012 commented on package.json
> +  "name": "@one",
Rename to "@one/core"

2021-12-29 11:57 UTC, asmanp2012 commented on tsconfig.json
> +    "target": "ES2020",
change target to 2019

2021-12-29 11:58 UTC, asmanp2012 commented on tsconfig.json
> +    "lib": ["es2020"],
Add this libs `ScriptHost`, `WebWorker`, `DOM`, `DOM.Iterable`

2021-12-29 11:59 UTC, asmanp2012 commented on tsconfig.json
> +    "skipLibCheck": true,
Add `outDir`

2021-12-29 12:08 UTC, asmanp2012 commented on .eslintignore
> +**/*.js
remove **/
and add `mjs`, `map`, `d.ts` type files

2021-12-29 12:08 UTC, asmanp2012 commented on .eslintignore
> +**/*.js
remove **/
and add `mjs`, `map`, `d.ts` type files

2021-12-29 12:11 UTC, asmanp2012 commented on .eslintrc
> +  "parserOptions": { "project": ["./tsconfig.json"] },
Make a copy of tsconfig file with the `ts-lint.json` name. and put this inside the "parserOptions"

2021-12-29 12:16 UTC, asmanp2012 commented on .eslintrc
> +    "@typescript-eslint/strict-boolean-expressions": [
Use `@typescript-eslint/no-inferrable-types` instead of this.

2021-12-29 12:16 UTC, asmanp2012 commented on .eslintrc
> +  "ignorePatterns": ["node_modules/"]
Remove this line.

2021-12-29 12:19 UTC, asmanp2012 requested changes
Complete the files list in ignore files and remove the extra config.

2021-12-29 19:14 UTC, njfamirm commented
ok?

2021-12-30 18:55 UTC, njfamirm commented
tsconfig additional commecnt was removed!

2021-12-30 20:39 UTC, asmanp2012 requested changes
Reject

2021-12-30 20:40 UTC, closed without merging