add first package and demo
AliMD/One pull request #3
Opened 2021-12-30 16:40 UTC by mm25zamanian

2021-12-30 20:11 UTC, asmanp2012 requested changes
Move all of the src files and directory to the root demo package directory.

2021-12-30 20:11 UTC, asmanp2012 commented on demo/tsconfig.json
> +    "dist",
change `"dist",` to `"*.d.ts",`

2021-12-30 20:11 UTC, asmanp2012 commented on package/util/package.json
> +  "main": "./dist/index.js",
change main to `index.js`

2021-12-30 20:11 UTC, asmanp2012 commented on package/util/package.json
> +    "tslib": "^2.2.0"
change `"tslib": "^2.2.0"` to `"tslib": "^2.3.1"`

2021-12-30 20:11 UTC, asmanp2012 commented on package/util/tsconfig.json
> +}
Add break end of the file.

2021-12-30 20:11 UTC, asmanp2012 commented on demo/package.json
> +  "main": "./dist/index.js",
change `"main": "./dist/index.js",`  to `"main": "index.js",`

2021-12-30 20:11 UTC, asmanp2012 commented on demo/src/util/index.html
> +<html lang="en">
Move all of the src file and directory to the root demo package directory.

2021-12-30 20:11 UTC, asmanp2012 commented on demo/src/util/index.html
> +<html lang="en">
Change to this
```HTML
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
</head>

<body>
  <h3>Check the console</h3>
  <script src="./index.js" type="module"></script>
</body>

</html>
```

2021-12-30 20:11 UTC, asmanp2012 commented on demo/package.json
> +  "main": "./dist/index.js",
Add `"type": "module",`

2021-12-30 20:11 UTC, asmanp2012 commented on package/util/package.json
> +  "main": "./dist/index.js",
Add `"type": "module",`

2021-12-31 06:51 UTC, asmanp2012 requested changes

2021-12-31 06:51 UTC, asmanp2012 commented on package.json
> +    "watch": "npm-run-all --parallel watch:*",
Remove all `watch` scripts.

2021-12-31 06:51 UTC, asmanp2012 commented on demo/tsconfig.json
> +}
?

2021-12-31 06:51 UTC, asmanp2012 commented on demo/src/util/index.html
> +<html lang="en">
?

2021-12-31 06:51 UTC, asmanp2012 commented on demo/src/index.html
> +<html lang="en">
Remove `src` and move all content to the root `demo` package directory.

2022-01-02 15:45 UTC, mm25zamanian commented
Ok ???
but please review eslint config !!!!

2022-01-02 20:08 UTC, asmanp2012 requested changes
remove extra scripts and fix import addres

2022-01-02 20:08 UTC, asmanp2012 commented on demo/util/index.ts
> +import { persianNumberToEnglishNumber } from "@one/util/src/persian-number";
change `@one/util/src/persian-number` to `@one/util/persian-number`

2022-01-02 20:08 UTC, asmanp2012 commented on package.json
> +  "license": "MIT",
Remove `license`

2022-01-02 20:08 UTC, asmanp2012 commented on package.json
> +    "serve": "node ./dist/src/server.js",
remove `serve`

2022-01-03 10:36 UTC, mm25zamanian commented
@asmanp2012 Please Merge pull !

2022-01-05 16:08 UTC, asmanp2012 approved these changes
All config is ok and doesn't have any problem.

2022-01-05 16:08 UTC, merged